# Generated by Django 2.0.7 on 2019-03-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0005_auto_20190312_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.IntegerField(choices=[(2, 'HTML'), (4, 'Javascript'), (5, 'CSS'), (3, 'SQL'), (0, 'Plain'), (1, 'Python')], default=0),
        ),
    ]
