# Generated by Django 2.0.7 on 2019-03-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0006_auto_20190312_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.IntegerField(choices=[(2, 'HTML'), (5, 'CSS'), (3, 'SQL'), (1, 'Python'), (0, 'Plain'), (4, 'Javascript')], default=0),
        ),
    ]
