# Generated by Django 2.0.7 on 2019-03-12 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0007_auto_20190312_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='users',
        ),
        migrations.AlterField(
            model_name='paste',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.IntegerField(choices=[(0, 'Plain'), (5, 'CSS'), (1, 'Python'), (4, 'Javascript'), (3, 'SQL'), (2, 'HTML')], default=0),
        ),
    ]
