# Generated by Django 2.0.7 on 2019-03-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0008_auto_20190312_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.IntegerField(choices=[(1, 'Python'), (4, 'Javascript'), (3, 'SQL'), (5, 'CSS'), (0, 'Plain'), (2, 'HTML')], default=0),
        ),
    ]
