# Generated by Django 2.0.7 on 2019-03-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0009_auto_20190313_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.IntegerField(choices=[(3, 'SQL'), (5, 'CSS'), (4, 'Javascript'), (1, 'Python'), (0, 'Plain'), (2, 'HTML')], default=0),
        ),
    ]
