# Generated by Django 2.0.7 on 2019-03-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0010_auto_20190313_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.IntegerField(choices=[(3, 'SQL'), (2, 'HTML'), (1, 'Python'), (5, 'CSS'), (4, 'Javascript'), (0, 'Plain')], default=0),
        ),
    ]
