# Generated by Django 2.0.7 on 2019-03-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0011_auto_20190314_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.IntegerField(choices=[(4, 'Javascript'), (3, 'SQL'), (2, 'HTML'), (1, 'Python'), (5, 'CSS'), (0, 'Plain')], default=0),
        ),
    ]
