# Generated by Django 2.0.7 on 2019-03-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0012_auto_20190314_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='generated_url',
            field=models.CharField(db_index=True, default='test', max_length=6),
        ),
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.IntegerField(choices=[(1, 'Python'), (3, 'SQL'), (2, 'HTML'), (4, 'Javascript'), (0, 'Plain'), (5, 'CSS')], default=0),
        ),
    ]
