# Generated by Django 2.0.7 on 2019-03-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0013_auto_20190314_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.IntegerField(choices=[(0, 'Plain'), (5, 'CSS'), (3, 'SQL'), (2, 'HTML'), (1, 'Python'), (4, 'Javascript')], default=0),
        ),
    ]
