# Generated by Django 2.0.7 on 2019-03-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0015_auto_20190314_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='generated_url',
            field=models.CharField(default='8anili', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.IntegerField(choices=[(2, 'HTML'), (1, 'Python'), (5, 'CSS'), (4, 'Javascript'), (0, 'Plain'), (3, 'SQL')], default=0),
        ),
    ]
