# Generated by Django 2.0.7 on 2019-03-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0016_auto_20190315_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='generated_url',
            field=models.CharField(default='xzghdr', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.IntegerField(choices=[(0, 'Plain'), (3, 'SQL'), (4, 'Javascript'), (5, 'CSS'), (1, 'Python'), (2, 'HTML')], default=0),
        ),
    ]
