# Generated by Django 2.0.7 on 2019-03-16 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastes', '0017_auto_20190315_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='shares',
            field=models.ManyToManyField(related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paste',
            name='content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='paste',
            name='generated_url',
            field=models.CharField(default='gvnnkx', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.IntegerField(choices=[(0, 'Plain'), (1, 'Python'), (2, 'HTML'), (3, 'SQL'), (5, 'CSS'), (4, 'Javascript')], default=0),
        ),
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
